//! Client-side E2E encryption for cloud sync.
//!
//! The encryption scheme is: passphrase → PBKDF2-HMAC-SHA256 → HKDF-SHA256 → AES-256-GCM.
//! The server stores only an opaque ciphertext blob and never sees the key or plaintext.
//!
//! # Key lifecycle
//!
//! 1. On first E2E setup: [`setup_e2e`] generates a random 16-byte salt, stretches the
//!    passphrase with PBKDF2, and derives the final key with HKDF.  The salt and
//!    iteration count are sent to the server via [`setup_e2e_on_server`]; the key is
//!    held in memory only for the duration of the session.
//!
//! 2. On subsequent app starts: the user re-enters their passphrase; [`restore_key`]
//!    fetches the stored salt from the server and re-derives the identical key.
//!
//! 3. If the passphrase is forgotten, cloud data is unrecoverable — by design.

use aes_gcm::{
    aead::{Aead, KeyInit},
    Aes256Gcm, Nonce,
};
use hkdf::Hkdf;
use rand::RngCore;
use sha2::Sha256;

use crate::state::BuildAttestation;

/// Number of PBKDF2 iterations.  600 000 matches OWASP 2023 recommendations
/// for PBKDF2-HMAC-SHA256.
const PBKDF2_ITERATIONS: u32 = 600_000;

/// HKDF context label — uniquely binds the derived key to this application and
/// version so keys cannot be reused across different protocols.
const HKDF_INFO: &[u8] = b"mylittlechart-sync-v1";

// =============================================================================
// Key derivation
// =============================================================================

/// Derive an AES-256 key from `passphrase` and `salt`.
///
/// Two-step derivation:
/// 1. PBKDF2-HMAC-SHA256 stretches the passphrase (CPU-hard).
/// 2. HKDF-SHA256 extracts and expands into the final key with a context label.
///
/// The `salt` must be the same bytes that were generated by [`generate_salt`]
/// and stored server-side.  Passing the wrong salt produces a different key and
/// decryption will fail with an authentication error.
pub fn derive_key(passphrase: &str, salt: &[u8]) -> [u8; 32] {
    // Step 1: PBKDF2 — slow by design to resist brute-force attacks.
    let mut pbkdf2_output = [0u8; 32];
    pbkdf2::pbkdf2_hmac::<Sha256>(
        passphrase.as_bytes(),
        salt,
        PBKDF2_ITERATIONS,
        &mut pbkdf2_output,
    );

    // Step 2: HKDF — domain-separate the key with an application-specific label.
    let hk = Hkdf::<Sha256>::new(Some(salt), &pbkdf2_output);
    let mut key = [0u8; 32];
    hk.expand(HKDF_INFO, &mut key).expect("HKDF expand failed — output length is valid");
    key
}

/// Generate a cryptographically random 16-byte salt and return it as a
/// 32-character lowercase hex string suitable for JSON storage.
pub fn generate_salt() -> String {
    let mut salt = [0u8; 16];
    rand::thread_rng().fill_bytes(&mut salt);
    hex::encode(salt)
}

// =============================================================================
// Encryption / decryption
// =============================================================================

/// Encrypt `plaintext` with `key` using AES-256-GCM.
///
/// Returns a `Vec<u8>` whose layout is:
/// ```text
/// [12-byte nonce][variable-length ciphertext + 16-byte GCM tag]
/// ```
///
/// A fresh random nonce is generated for every call — never reuse a key+nonce
/// pair.  The AES-GCM tag provides both confidentiality and integrity; passing
/// tampered ciphertext to [`decrypt`] will return an error.
pub fn encrypt(key: &[u8; 32], plaintext: &[u8]) -> Result<Vec<u8>, String> {
    let cipher = Aes256Gcm::new_from_slice(key)
        .map_err(|e| format!("cipher init: {}", e))?;

    let mut nonce_bytes = [0u8; 12];
    rand::thread_rng().fill_bytes(&mut nonce_bytes);
    let nonce = Nonce::from_slice(&nonce_bytes);

    let ciphertext = cipher
        .encrypt(nonce, plaintext)
        .map_err(|e| format!("encrypt: {}", e))?;

    let mut result = Vec::with_capacity(12 + ciphertext.len());
    result.extend_from_slice(&nonce_bytes);
    result.extend_from_slice(&ciphertext);
    Ok(result)
}

/// Decrypt data produced by [`encrypt`].
///
/// Expects `data` to be at least 12 bytes (nonce prefix).  Returns the
/// plaintext on success, or an error string if the data is too short,
/// the key is wrong, or the ciphertext has been tampered with.
pub fn decrypt(key: &[u8; 32], data: &[u8]) -> Result<Vec<u8>, String> {
    if data.len() < 12 {
        return Err(format!(
            "data too short: {} bytes (minimum 12 for nonce)",
            data.len()
        ));
    }

    let cipher = Aes256Gcm::new_from_slice(key)
        .map_err(|e| format!("cipher init: {}", e))?;

    let nonce = Nonce::from_slice(&data[..12]);
    cipher
        .decrypt(nonce, &data[12..])
        .map_err(|e| format!("decrypt: {}", e))
}

// =============================================================================
// E2E setup helpers
// =============================================================================

/// Parameters to register with the server when setting up E2E for the first time.
///
/// The server stores these so that the user's key can be re-derived on the next
/// login without asking for additional information beyond the passphrase.
pub struct E2ESetupParams {
    /// Hex-encoded 16-byte random salt.
    pub salt: String,
    /// Number of PBKDF2 iterations used during key derivation.
    pub iterations: i32,
}

/// Set up E2E encryption for a new passphrase.
///
/// Generates a fresh salt, derives the AES-256 key, and returns both the key
/// (for in-memory use this session) and the [`E2ESetupParams`] that must be
/// sent to the server via [`setup_e2e_on_server`].
///
/// The key is **never** stored on disk or transmitted to the server.
pub fn setup_e2e(passphrase: &str) -> ([u8; 32], E2ESetupParams) {
    let salt = generate_salt();
    let salt_bytes = hex::decode(&salt).expect("salt was just generated as valid hex");
    let key = derive_key(passphrase, &salt_bytes);
    (
        key,
        E2ESetupParams {
            salt,
            iterations: PBKDF2_ITERATIONS as i32,
        },
    )
}

/// Restore the E2E key from a known passphrase and the salt stored server-side.
///
/// Call this after the user enters their passphrase on app restart.  Fetch the
/// salt first with [`get_e2e_params`].
pub fn restore_key(passphrase: &str, salt_hex: &str) -> Result<[u8; 32], String> {
    let salt_bytes = hex::decode(salt_hex)
        .map_err(|e| format!("invalid salt hex: {}", e))?;
    Ok(derive_key(passphrase, &salt_bytes))
}

// =============================================================================
// HTTP helpers
// =============================================================================

/// Fetch the E2E parameters stored on the server for the authenticated user.
///
/// Returns `Some((salt_hex, iterations))` if E2E has been set up, or `None`
/// if the user has not yet enabled E2E encryption.
pub async fn get_e2e_params(
    client: &reqwest::Client,
    server_url: &str,
    token: &str,
) -> Result<Option<(String, i32)>, String> {
    let resp = client
        .get(format!("{}/api/sync/e2e-params", server_url))
        .bearer_auth(token)
        .timeout(std::time::Duration::from_secs(10))
        .send()
        .await
        .map_err(|e| format!("e2e-params request: {}", e))?;

    if resp.status() == reqwest::StatusCode::NOT_FOUND {
        return Ok(None);
    }

    if !resp.status().is_success() {
        return Err(format!("e2e-params: HTTP {}", resp.status()));
    }

    #[derive(serde::Deserialize)]
    struct E2EParamsResponse {
        salt: String,
        iterations: i32,
    }

    let data: E2EParamsResponse = resp
        .json()
        .await
        .map_err(|e| format!("e2e-params parse: {}", e))?;

    Ok(Some((data.salt, data.iterations)))
}

/// Register E2E parameters on the server.
///
/// Call this once after [`setup_e2e`].  The server stores the salt and
/// iteration count so the key can be re-derived from the passphrase on the
/// next session without any additional input.
///
/// The server must treat the stored parameters as immutable — changing them
/// would invalidate all existing encrypted blobs.
pub async fn setup_e2e_on_server(
    client: &reqwest::Client,
    server_url: &str,
    token: &str,
    salt: &str,
    iterations: i32,
    build_attest: &BuildAttestation,
) -> Result<(), String> {
    #[derive(serde::Serialize)]
    struct E2ESetupRequest<'a> {
        salt: &'a str,
        iterations: i32,
    }

    let builder = client
        .post(format!("{}/api/sync/e2e-setup", server_url))
        .bearer_auth(token)
        .json(&E2ESetupRequest { salt, iterations })
        .timeout(std::time::Duration::from_secs(10));

    let builder = crate::attest::with_attestation(builder, build_attest);

    let resp = builder
        .send()
        .await
        .map_err(|e| format!("e2e-setup request: {}", e))?;

    if !resp.status().is_success() {
        return Err(format!("e2e-setup: HTTP {}", resp.status()));
    }

    Ok(())
}
