//! E2E key management — vault salt storage and recovery key support.
//!
//! This module handles uploading vault parameters (salt, encrypted master key)
//! to the server so that vault recovery is possible on another device.
//!
//! CloudSync items are NOT encrypted client-side; this module's HTTP helpers
//! exist solely for vault recovery purposes (salt + encrypted_master_key stored
//! server-side).
//!
//! The `encrypt`/`decrypt` functions are available for ZtBlob-tier items that
//! need client-side encryption before push (future: custom indicators, strategies).
//!
//! Key derivation (`derive_key`, `restore_key`) is used during vault unlock to
//! produce the master key from the passphrase and salt.  Domain separation from
//! vault encryption is enforced by the HKDF info string: sync uses
//! `"mylittlechart-sync-v1"`, vault uses `"mylittlechart-vault-v1"`.
//!
//! All cryptographic primitives are delegated to [`zengeld_chart::crypto`].

use zengeld_chart::crypto as crypto;

use crate::state::BuildAttestation;

/// Number of PBKDF2 iterations — re-exported for callers that need it.
pub const PBKDF2_ITERATIONS: u32 = crypto::PBKDF2_ITERATIONS;

// =============================================================================
// Key derivation
// =============================================================================

/// Derive an AES-256 sync key from `passphrase` and `salt`.
///
/// Two-step derivation:
/// 1. PBKDF2-HMAC-SHA256 stretches the passphrase into a master_key (CPU-hard).
/// 2. HKDF-SHA256 with info=`"mylittlechart-sync-v1"` derives the final sync key.
///
/// The `salt` must be the same bytes that were generated by [`generate_salt`]
/// and stored server-side.  Passing the wrong salt produces a different key and
/// decryption will fail with an authentication error.
///
/// The PBKDF2 intermediate (master_key) is zeroed after use.
pub fn derive_key(passphrase: &str, salt: &[u8]) -> [u8; 32] {
    let mut master = crypto::derive_master_key(passphrase, salt);
    let sync_key = crypto::derive_sync_key(&master, salt);
    // Zero the intermediate master key after deriving the sync key
    master.fill(0);
    sync_key
}

/// Generate a cryptographically random 16-byte salt and return it as a
/// 32-character lowercase hex string suitable for JSON storage.
pub fn generate_salt() -> String {
    hex::encode(crypto::generate_salt())
}

// =============================================================================
// Encryption / decryption
// =============================================================================

/// Encrypt `plaintext` with `key` using AES-256-GCM.
///
/// Returns a `Vec<u8>` whose layout is:
/// ```text
/// [12-byte nonce][variable-length ciphertext + 16-byte GCM tag]
/// ```
///
/// A fresh random nonce is generated for every call — never reuse a key+nonce
/// pair.  The AES-GCM tag provides both confidentiality and integrity; passing
/// tampered ciphertext to [`decrypt`] will return an error.
pub fn encrypt(key: &[u8; 32], plaintext: &[u8]) -> Result<Vec<u8>, String> {
    crypto::encrypt(key, plaintext)
}

/// Decrypt data produced by [`encrypt`].
///
/// Expects `data` to be at least 28 bytes (12 nonce + 16 tag).  Returns the
/// plaintext on success, or an error string if the data is too short,
/// the key is wrong, or the ciphertext has been tampered with.
pub fn decrypt(key: &[u8; 32], data: &[u8]) -> Result<Vec<u8>, String> {
    crypto::decrypt(key, data)
}

// =============================================================================
// E2E setup helpers
// =============================================================================

/// Parameters to register with the server when setting up E2E for the first time.
///
/// The server stores these so that the user's key can be re-derived on the next
/// login without asking for additional information beyond the passphrase.
pub struct E2ESetupParams {
    /// Hex-encoded 16-byte random salt.
    pub salt: String,
    /// Number of PBKDF2 iterations used during key derivation.
    pub iterations: i32,
    /// Optional AES-256-GCM blob containing the master key encrypted with the
    /// user's recovery key (base64-encoded for JSON transport).
    ///
    /// When present, the server stores it in `sync_e2e_params.encrypted_master_key`
    /// so that the user can recover their master key if they forget their passphrase.
    /// The server never decrypts or inspects this blob.
    pub encrypted_master_key: Option<Vec<u8>>,
}

/// Set up E2E encryption for a new passphrase.
///
/// Generates a fresh salt, derives the AES-256 sync key, and returns both the
/// key (for in-memory use this session) and the [`E2ESetupParams`] that must be
/// sent to the server via [`setup_e2e_on_server`].
///
/// The key is **never** stored on disk or transmitted to the server.
pub fn setup_e2e(passphrase: &str) -> ([u8; 32], E2ESetupParams) {
    let salt = generate_salt();
    let salt_bytes = hex::decode(&salt).expect("salt was just generated as valid hex");
    let key = derive_key(passphrase, &salt_bytes);
    (
        key,
        E2ESetupParams {
            salt,
            iterations: PBKDF2_ITERATIONS as i32,
            encrypted_master_key: None,
        },
    )
}

/// Restore the E2E key from a known passphrase and the salt stored server-side.
///
/// Call this after the user enters their passphrase on app restart.  Fetch the
/// salt first with [`get_e2e_params`].
pub fn restore_key(passphrase: &str, salt_hex: &str) -> Result<[u8; 32], String> {
    let salt_bytes = hex::decode(salt_hex)
        .map_err(|e| format!("invalid salt hex: {}", e))?;
    Ok(derive_key(passphrase, &salt_bytes))
}

// =============================================================================
// HTTP helpers
// =============================================================================

/// Fetch the E2E parameters stored on the server for the authenticated user.
///
/// Returns `Some((salt_hex, iterations))` if E2E has been set up, or `None`
/// if the user has not yet enabled E2E encryption.
pub async fn get_e2e_params(
    client: &reqwest::Client,
    server_url: &str,
    token: &str,
    profile_id: &str,
    device_id: &str,
) -> Result<Option<(String, i32)>, String> {
    let resp = client
        .get(format!("{}/api/sync/e2e-params", server_url))
        .bearer_auth(token)
        .header("X-Profile-Id", profile_id)
        .header("X-Device-Id", device_id)
        .timeout(std::time::Duration::from_secs(10))
        .send()
        .await
        .map_err(|e| format!("e2e-params request: {}", e))?;

    if resp.status() == reqwest::StatusCode::NOT_FOUND {
        return Ok(None);
    }

    if !resp.status().is_success() {
        return Err(format!("e2e-params: HTTP {}", resp.status()));
    }

    #[derive(serde::Deserialize)]
    struct E2EParamsResponse {
        salt: String,
        iterations: i32,
    }

    let data: E2EParamsResponse = resp
        .json()
        .await
        .map_err(|e| format!("e2e-params parse: {}", e))?;

    Ok(Some((data.salt, data.iterations)))
}

/// Register E2E parameters on the server.
///
/// Call this once after [`setup_e2e`].  The server stores the salt and
/// iteration count so the key can be re-derived from the passphrase on the
/// next session without any additional input.
///
/// Pass `encrypted_master_key` (a raw AES-GCM blob) to also store the
/// recovery-key-wrapped master key on the server.  The server stores this as
/// an opaque blob and never inspects its contents.  Pass `None` to skip.
///
/// The server must treat the stored parameters as immutable — changing them
/// would invalidate all existing encrypted blobs.
pub async fn setup_e2e_on_server(
    client: &reqwest::Client,
    server_url: &str,
    token: &str,
    salt: &str,
    iterations: i32,
    encrypted_master_key: Option<&[u8]>,
    build_attest: &BuildAttestation,
    profile_id: &str,
    device_id: &str,
) -> Result<(), String> {
    #[derive(serde::Serialize)]
    struct E2ESetupRequest<'a> {
        salt: &'a str,
        iterations: i32,
        #[serde(skip_serializing_if = "Option::is_none")]
        encrypted_master_key: Option<String>,
    }

    use base64::Engine as _;
    let emk_b64 = encrypted_master_key
        .map(|b| base64::engine::general_purpose::STANDARD.encode(b));

    let builder = client
        .post(format!("{}/api/sync/e2e-setup", server_url))
        .bearer_auth(token)
        .header("X-Profile-Id", profile_id)
        .header("X-Device-Id", device_id)
        .json(&E2ESetupRequest {
            salt,
            iterations,
            encrypted_master_key: emk_b64,
        })
        .timeout(std::time::Duration::from_secs(10));

    let builder = crate::attest::with_attestation(builder, build_attest);

    let resp = builder
        .send()
        .await
        .map_err(|e| format!("e2e-setup request: {}", e))?;

    if !resp.status().is_success() {
        return Err(format!("e2e-setup: HTTP {}", resp.status()));
    }

    Ok(())
}
